### ISSUE TITLE
Enhance Credit Risk Model Evaluation with Comprehensive Metrics 

### ISSUE THREAD

**Issue by FreeSpirit11** [Akshat111111/Hedging-of-Financial-Derivatives#171]
**Is your feature request related to a problem? Please describe.**

In "Hedging-of-Financial-Derivatives/Credit Risk /CreditRisk.ipynb" Existing model evaluation methods provide limited insights, hindering our ability to optimize models effectively.I want to Use a variety of metrics like ROC-AUC, Precision-Recall, F1-score, and Confusion Matrix in addition to accuracy to get a more comprehensive understanding of model performance.

**Describe the solution you'd like**

Implement a "Comprehensive Model Evaluation" section with advanced metrics and visualizations for a deeper understanding of model performance.

**Describe alternatives you've considered**

Manual calculation of additional metrics or external tools may be used, but they are time-consuming and error-prone.

**Additional context**

This feature will elevate our model assessment practices, providing invaluable insights to drive performance improvements.

**Comment by FreeSpirit11** [comment]
Hi @Akshat111111 , I have raised this issue . Please assign it to me.

**Comment by FreeSpirit11** [comment]
@aryan1165 , This issue is already assigned to me. You can work on some other issue. And please don't do such kind of thing with other issues as well. If someone is assigned to an issue you can't just solve that issue yourself because you were not assigned to that task. By doing this, you are ruining the hard work of others.

**Comment by Akshat111111** [comment]
> @aryan1165 , This issue is already assigned to me. You can work on some other issue. And please don't do such kind of thing with other issues as well. If someone is assigned to an issue you can't just solve that issue yourself because you were not assigned to that task. By doing this, you are ruining the hard work of others.

I totally agree with you.Keep this in your mind @aryan1165 for the next time.

**Comment by aryan1165** [comment]
I'll make sure to keep that in mind for the next time. But in my view in open source, people open issues to let others solve them, The word "Issue" means that only, you cannot solve that issue and you post it in public. Now, everyone has opened an issue and working on it for several days creating a creative block in the repository. @Akshat111111 If I feel I can solve that issue faster should I post a comment to get assigned or people who post the issue should not be assigned and everyone should solve issues posted by others. Please guide me. Because i cant think of new issues in the repository but i can solve them really efficiently.

**Comment by Saswatsusmoy** [comment]
@Akshat111111 


Having worked on various well managed and maintained Open-Source repos, I can vouch for anyone to work on a issue without being assigned because working on a issue can be and is a very tedious and progressive task. If any PR is being raised, irrespective of the creator of the issue and the assigned folks it should be given a heed without any prior bias. It isn't about just creating and solving a issue, Open-Source Contributions literally mean to work in collaboration so as to enhance any product or get better and innovative solutions to an Issue. If you feel a particular PR isn't worth to be merged or requires any more enhancements, it should communicated to the whole community so as to reduce conflict of interests.


@aryan1165 might not be wrong to raise a PR to an issue earlier than the assigned person. Issues are for the whole community to work upon rather than the assigned person only. An accurate implementation with proper documented code was merged as a PR which was raised quicker than anyone else shouldn't be a problem for any community, if it wants to grow to a certain reputable level. Open-Source contributions doesn't only mean contributing during the Summer of Code periods, so a more collaborative approach to solving issues is appreciated by all contributors.

**Comment by Akshat111111** [comment]
Yeah, I totally agree with you
