### ISSUE TITLE
Stock market prediction 

### ISSUE THREAD

**Issue by amishhaa** [Akshat111111/Hedging-of-Financial-Derivatives#258]
**Is your feature request related to a problem? Please describe.**
Not related to a problem,
I would like to use yahoo finance api to get real time data and predict stock market prices using features like INR GDP Nifty.

**Describe the solution you'd like**
Even though stock market nifty prediction models already exist in this repo I would like to generalise it as the current implementations use data upto 2023 which might not be relevant 2-3 years later and updating it regularly is a tedious task hence using APIs is a smart option 

**Describe alternatives you've considered**
//

**Additional context**
//

**Comment by amishhaa** [comment]
I request to be assigned

**Comment by samriddh-i** [comment]
i would like to work on this issue please assign

**Comment by Akshat111111** [comment]
> i would like to work on this issue please assign

Tell me your approach, Its should be something new and unique

**Comment by samriddh-i** [comment]
i would like to enhance data collection and preparation Instead of relying on a single data source, i would like to aggregate data from multiple sources (Yahoo Finance, Google Finance, Alpha Vantage, etc.) to ensure data accuracy and completeness.
Feature Engineering: Integrate additional relevant features such as trading volume, moving averages, technical indicators (e.g., RSI, MACD), and macroeconomic indicators (e.g., interest rates, GDP growth).
Data Cleaning and Preprocessing: Ensure thorough data cleaning, handling missing values, and normalizing data to improve model performance.

**Comment by Akshat111111** [comment]
This work is already done
