### ISSUE TITLE
Decentralized Finance (DeFi) Integration

### ISSUE THREAD

**Issue by Akshat111111** [Akshat111111/Hedging-of-Financial-Derivatives#62]
You can implement using any of the existing technologies

**Comment by tejasvinigoel** [comment]
Im interested, kindly assign it to me

**Comment by tejasvinigoel** [comment]
@Akshat111111 im facing this error while trying to pull and push due to invalid paths in the indian election folder... I deleted my previously cloned copy from my laptop and now im not able to clone the repo again.. kindly help


 git clone https://github.com/tejasvinigoel/Hedging-of-Financial-Derivatives.git
Cloning into 'Hedging-of-Financial-Derivatives'...
remote: Enumerating objects: 1070, done.
remote: Counting objects: 100% (635/635), done.
remote: Compressing objects: 100% (449/449), done.
remote: Total 1070 (delta 292), reused 455 (delta 170), pack-reused 435
Receiving objects: 100% (1070/1070), 92.45 MiB | 13.43 MiB/s, done.
Resolving deltas: 100% (346/346), done.
error: invalid path 'Indian Elections/indian_election_preditiction /.DS_Store'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by Akshat111111** [comment]
> @Akshat111111 im facing this error while trying to pull and push due to invalid paths in the indian election folder... I deleted my previously cloned copy from my laptop and now im not able to clone the repo again.. kindly help
> 
> git clone https://github.com/tejasvinigoel/Hedging-of-Financial-Derivatives.git Cloning into 'Hedging-of-Financial-Derivatives'... remote: Enumerating objects: 1070, done. remote: Counting objects: 100% (635/635), done. remote: Compressing objects: 100% (449/449), done. remote: Total 1070 (delta 292), reused 455 (delta 170), pack-reused 435 Receiving objects: 100% (1070/1070), 92.45 MiB | 13.43 MiB/s, done. Resolving deltas: 100% (346/346), done. error: invalid path 'Indian Elections/indian_election_preditiction /.DS_Store' fatal: unable to checkout working tree warning: Clone succeeded, but checkout failed. You can inspect what was checked out with 'git status' and retry with 'git restore --source=HEAD :/'

try via vs code
