### ISSUE TITLE
2024 Indian election sentimental analysis

### ISSUE THREAD

**Issue by Akshat111111** [Akshat111111/Hedging-of-Financial-Derivatives#63]
The task is to find the sentiments and corelation with financial market movement.

**Comment by apooyadv** [comment]
Assign this to me.I'll use rnns for it.

**Comment by diptarup794** [comment]
Hi! I have previous experience working with nlp . Please assign this issue to me @Akshat111111

**Comment by tejasvinigoel** [comment]
Im interested in this, kindly assign it to me

**Comment by Akshat111111** [comment]
I have assigned you all.Firstly clarify your idea/approach so that there should not be any overlapping of work.

**Comment by apooyadv** [comment]
Could you please describe it a little more?

**Comment by Akshat111111** [comment]
> Could you please describe it a little more?

You can simultaneously plot the sentiment of common people with the plot of nifty.Also both the things should be present in the same plot.

**Comment by milliondreamsblog** [comment]
Approch -
Sentiment Analysis:
Using transformer-based models like BERT or DistilBERT(because its lite on space) for sentiment analysis.
Fine-tuning these models on Indian political news articles and Twitter posts .
Utilizing a 5-point rating scale (very good, good, moderate, bad, very bad) can provide granularity in sentiment analysis, which can be helpful for market analysis.

Analyzing financial market movements, could use time series analysis techniques - ARIMA(fanckly idk this part yet)

finally ,
correlation analysis to identify any relationships between sentiment and market movements with techniques such as Pearson correlation coefficient.


Please assign me as well would love learn and contribute.

**Comment by Akshat111111** [comment]
> Approch - Sentiment Analysis: Using transformer-based models like BERT or DistilBERT(because its lite on space) for sentiment analysis. Fine-tuning these models on Indian political news articles and Twitter posts . Utilizing a 5-point rating scale (very good, good, moderate, bad, very bad) can provide granularity in sentiment analysis, which can be helpful for market analysis.
> 
> Analyzing financial market movements, could use time series analysis techniques - ARIMA(fanckly idk this part yet)
> 
> finally , correlation analysis to identify any relationships between sentiment and market movements with techniques such as Pearson correlation coefficient.
> 
> Please assign me as well would love learn and contribute.

yeah your idea is good, so I will suggest you to create a new issue specifying your model name  and start working on it

**Comment by milliondreamsblog** [comment]
hey I have created a new issue , issue has not being assigned tag of gssoc24

**Comment by Akshat111111** [comment]
Which issue ??
